services:
  backend:
    image: vanphu2005/mern-backend:1.0
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      PORT: ${PORT}

  frontend:
    image: vanphu2005/mern-frontend:2.0
    ports:
      - "5173:4173"